RSpec.shared_context 'responses' do
  let(:properties) do
    {
      'getProperties' => [{
        "name"=>"Test",
        "propId"=>"1",
        "propTypeId"=>"1",
        "ownerId"=>"1",
        "currency"=>"CAD",
        "address"=>"Address Line",
        "city"=>"Toronto",
        "state"=>"ON",
        "country"=>"CA",
        "postcode"=>"",
        "latitude"=>"43",
        "longitude"=>"-79",
        "roomTypes"=> [{
          "name"=>"Room",
          "qty"=>"1",
          "roomId"=>"1",
          "minPrice"=>"0.00",
          "maxPeople"=>"2",
          "maxAdult"=>"0",
          "maxChildren"=>"0",
          "unitAllocationPerGuest"=>"0",
          "unitNames"=>"1111"
        }]
      }]
    }
  end

  let(:property) do
    {
      'getProperty' => [{
        "name"=>"Test",
        "propId"=>"1",
        "propTypeId"=>"1",
        "ownerId"=>"1",
        "currency"=>"CAD",
        "address"=>"Address Line",
        "city"=>"Toronto",
        "state"=>"ON",
        "country"=>"CA",
        "postcode"=>"",
        "latitude"=>"43",
        "longitude"=>"-79",
        "roomTypes"=> [{
          "name"=>"Room",
          "qty"=>"1",
          "roomId"=>"1",
          "minPrice"=>"0.00",
          "maxPeople"=>"2",
          "maxAdult"=>"0",
          "maxChildren"=>"0",
          "unitAllocationPerGuest"=>"0",
          "unitNames"=>"1111"
        }]
      }]
    }
  end

  let(:bookings) do
    [{"bookId"=>"1",
      "roomId"=>"1",
      "unitId"=>"1",
      "roomQty"=>"1",
      "status"=>"1",
      "firstNight"=>"2019-07-01",
      "lastNight"=>"2019-07-11",
      "numAdult"=>"1",
      "numChild"=>"0",
      "guestTitle"=>"",
      "guestFirstName"=>"John",
      "guestName"=>"Doe",
      "guestEmail"=>"johndoe@email.com",
      "guestPhone"=>"+12 3456 789012",
      "guestMobile"=>"",
      "guestFax"=>"",
      "guestCompany"=>"",
      "guestAddress"=>"",
      "guestCity"=>"",
      "guestState"=>"",
      "guestPostcode"=>"",
      "guestCountry"=>"",
      "guestCountry2"=>"",
      "guestArrivalTime"=>"",
      "guestVoucher"=>"",
      "guestComments"=>"",
      "notes"=>"",
      "message"=>"",
      "groupNote"=>"",
      "custom1"=>"",
      "custom2"=>"",
      "custom3"=>"",
      "custom4"=>"",
      "custom5"=>"",
      "custom6"=>"",
      "custom7"=>"",
      "custom8"=>"",
      "custom9"=>"",
      "custom10"=>"",
      "flagColor"=>"007f7f",
      "flagText"=>"PAID AND VERIFIED ID (AIRBNB)",
      "statusCode"=>"0",
      "lang"=>"",
      "price"=>"0.00",
      "deposit"=>"0.00",
      "tax"=>"0.00",
      "commission"=>"0.00",
      "currency"=>"CAD",
      "rateDescription"=>"",
      "offerId"=>"0",
      "referer"=>"Airbnb.com",
      "refererEditable"=>"Airbnb.com",
      "reference"=>"",
      "apiSource"=>"10",
      "apiReference"=>"Test",
      "apiMessage"=>"Verified Response",
      "allowChannelUpdate"=>"1",
      "allowAutoAction"=>"1",
      "allowReview"=>"1",
      "propId"=>"1",
      "ownerId"=>"1",
      "bookingTime"=>"2018-05-02 22:52:57",
      "modified"=>"2018-06-29 00:35:09",
      "masterId"=>""},
     {"bookId"=>"1",
      "roomId"=>"1",
      "unitId"=>"1",
      "roomQty"=>"1",
      "status"=>"0",
      "firstNight"=>"2019-07-08",
      "lastNight"=>"2019-07-10",
      "numAdult"=>"2",
      "numChild"=>"0",
      "guestTitle"=>"",
      "guestFirstName"=>"Jane",
      "guestName"=>"Doe",
      "guestEmail"=>"janedoe@email.com",
      "guestPhone"=>"+12 345 67890",
      "guestMobile"=>"",
      "guestFax"=>"",
      "guestCompany"=>"",
      "guestAddress"=>"Any street1 Any street2\n" + "MA",
      "guestCity"=>"Any city",
      "guestState"=>"",
      "guestPostcode"=>"98004",
      "guestCountry"=>"US",
      "guestCountry2"=>"US",
      "guestArrivalTime"=>"",
      "guestVoucher"=>"",
      "guestComments"=>
       "1 Queen Bed and 1 Double Sofa Bed\n" +
       "Non-Smoking\n" +
       "Collect Payment From Guest.\n",
      "notes"=>"Transferred from 6101 to 1602\n",
      "message"=>"",
      "groupNote"=>"",
      "custom1"=>"",
      "custom2"=>"",
      "custom3"=>"",
      "custom4"=>"",
      "custom5"=>"",
      "custom6"=>"",
      "custom7"=>"",
      "custom8"=>"",
      "custom9"=>"",
      "custom10"=>"",
      "flagColor"=>"ff0000",
      "flagText"=>"NOT PAID",
      "statusCode"=>"0",
      "lang"=>"en",
      "price"=>"780.48",
      "deposit"=>"0.00",
      "tax"=>"89.79",
      "commission"=>"0.00",
      "currency"=>"CAD",
      "rateDescription"=>"",
      "offerId"=>"0",
      "referer"=>"A-Expedia",
      "refererEditable"=>"A-Expedia",
      "reference"=>"",
      "apiSource"=>"14",
      "apiReference"=>"1",
      "apiMessage"=>"",
      "allowChannelUpdate"=>"1",
      "allowAutoAction"=>"1",
      "allowReview"=>"1",
      "propId"=>"1",
      "ownerId"=>"1",
      "bookingTime"=>"2018-06-01 04:50:12",
      "modified"=>"2018-06-25 07:58:15",
      "masterId"=>""}]
  end
end